### ISSUE TITLE
It does not preserve the HTML formatting

### ISSUE THREAD

**Issue by maestrokame** [bill-long/angular-rich-text-diff#3]
Hello Bill,

This directive is exactly what I am looking for but the Plunker example on README.md does not preserve the diff's HTML formatting.

Is this a bug or am I missing something?

**Comment by bill-long** [comment]
The plunk is a bit out of date. IIRC, it tries to preserve the HTML formatting, but it isn't terribly smart about it. I'll see if I can get it updated in the next few days so at least the plunk reflects the behavior of the latest iteration.

**Comment by ruben-elumen** [comment]
Great to know about that because I need to keep only the basic structure such as <p>, <br> and <ul> (and if possible <table>). Thanks.

**Comment by bill-long** [comment]
I updated the plunk with the latest js. If this doesn't preserve the HTML you want to preserve, then unfortunately, you'll probably need to fix it yourself. I'll be happy to take a pull request. The project I was using this for has moved to Angular 2.0, so I'm not putting my time into this version anymore.
